@extends('layouts.app')

@section('title', 'Laporan')

@section('content')
<div class="flex items-center justify-between gap-3">
    <div>
        <h1 class="text-xl font-semibold">Laporan</h1>
        <p class="text-sm text-gray-500">Ringkasan transaksi masuk/keluar dan penyesuaian.</p>
    </div>
    <a href="{{ route('laporans.create') }}"
       class="inline-flex items-center rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white hover:bg-indigo-700">
        + Buat Laporan
    </a>
</div>

<div class="mt-6 overflow-x-auto rounded-xl border">
    <table class="min-w-full divide-y divide-gray-200">
        <thead class="bg-gray-50">
        <tr class="text-left text-xs font-semibold uppercase tracking-wide text-gray-600">
            <th class="px-4 py-3">ID</th>
            <th class="px-4 py-3">Tanggal</th>
            <th class="px-4 py-3">Jenis</th>
            <th class="px-4 py-3">Total Masuk</th>
            <th class="px-4 py-3">Total Keluar</th>
            <th class="px-4 py-3">Total Penyesuaian</th>
            <th class="px-4 py-3">Generated By</th>
        </tr>
        </thead>
        <tbody class="divide-y divide-gray-100 bg-white">
        @forelse($laporans as $l)
            <tr class="text-sm">
                <td class="px-4 py-3 text-gray-700">{{ $l->ID_Laporan }}</td>
                <td class="px-4 py-3 text-gray-700">{{ \Carbon\Carbon::parse($l->Tanggal_Laporan)->format('d/m/Y H:i') }}</td>
                <td class="px-4 py-3">
                    <span class="inline-flex rounded-full bg-gray-100 px-2 py-1 text-xs font-semibold text-gray-800">
                        {{ $l->Jenis_Laporan }}
                    </span>
                </td>
                <td class="px-4 py-3 text-gray-700">{{ $l->Total_Masuk }}</td>
                <td class="px-4 py-3 text-gray-700">{{ $l->Total_Keluar }}</td>
                <td class="px-4 py-3 text-gray-700">{{ $l->Total_Penyesuaian }}</td>
                <td class="px-4 py-3 text-gray-700">{{ $l->user->name ?? '-' }}</td>
            </tr>
        @empty
            <tr>
                <td colspan="7" class="px-4 py-10 text-center text-sm text-gray-500">
                    Belum ada laporan.
                </td>
            </tr>
        @endforelse
        </tbody>
    </table>
</div>

@if(method_exists($laporans, 'links'))
    <div class="mt-4">{{ $laporans->links() }}</div>
@endif
@endsection
